[default]
now_iso = "@jinja {{this._get_now_iso(this.tz)}}"
start_ts = "@jinja {{this._get_start_ts(this.tz)}}"
tz = "Asia/Kolkata"

[default.output]
base = "/tmp/output"

[default.logs]
base = "/tmp/logs"
enable_file = false
enable_stream = true
file = "@jinja {{this.logs.base}}/{{this._get_start_ts(this.tz).strftime('%Y-%m-%d_%H-%M-%S')}}.log"
level = "INFO"
name = 'default'
